# Generated by Django 5.1.6 on 2025-02-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='location',
        ),
    ]
