databases:
  - name: mysite2db
    plan: free
    databaseName: mysite2
    user: mysite2

services:
  - type: web
    plan: free
    name: mysite2
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn enceptics.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite2db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
