databases:
  - name: encepticsdb
    plan: free
    databaseName: enceptics_db
    user: enceptics

services:
  - type: web
    plan: free
    name: enceptics
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn enceptics.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: encepticsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
