databases:
  - name: enceptics-v2
    plan: free
    databaseName: enceptics-v2
    user: enceptics-v2

services:
  - type: web
    plan: free
    name: enceptics-v2
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn enceptics.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: enceptics_v2_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
