# Generated by Django 4.2.1 on 2023-10-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
