# Generated by Django 4.2.1 on 2025-01-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='booking_trend',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='place',
            name='revenue_forecast',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='place',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='total_canceled_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='total_completed_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='place',
            name='total_pending_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='total_visitors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
