# Generated by Django 5.1.6 on 2025-02-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='contracts/'),
        ),
    ]
